// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS_PxOM-cIJnrlOtkf3ee9JXs7wSPWZWU',
    appId: '1:664584052415:web:d1a8169e9435647396700a',
    messagingSenderId: '664584052415',
    projectId: 'financetracker-c4449',
    authDomain: 'financetracker-c4449.firebaseapp.com',
    storageBucket: 'financetracker-c4449.firebasestorage.app',
    measurementId: 'G-98LFPH510W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUhZKEnPIZ-0ArpC3v_ug8xDHWKGflIk',
    appId: '1:664584052415:android:76242bad508b249596700a',
    messagingSenderId: '664584052415',
    projectId: 'financetracker-c4449',
    storageBucket: 'financetracker-c4449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qiV0tUAVu5WlC9QoYvmLA5N0ReRpBPo',
    appId: '1:664584052415:ios:77c2ad9ab98d7a9996700a',
    messagingSenderId: '664584052415',
    projectId: 'financetracker-c4449',
    storageBucket: 'financetracker-c4449.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qiV0tUAVu5WlC9QoYvmLA5N0ReRpBPo',
    appId: '1:664584052415:ios:77c2ad9ab98d7a9996700a',
    messagingSenderId: '664584052415',
    projectId: 'financetracker-c4449',
    storageBucket: 'financetracker-c4449.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS_PxOM-cIJnrlOtkf3ee9JXs7wSPWZWU',
    appId: '1:664584052415:web:a2a84cbb4eb199ee96700a',
    messagingSenderId: '664584052415',
    projectId: 'financetracker-c4449',
    authDomain: 'financetracker-c4449.firebaseapp.com',
    storageBucket: 'financetracker-c4449.firebasestorage.app',
    measurementId: 'G-1G10G7VGZP',
  );

}